name: Get versions of products
# Intended to be called by other repositories to provide output versions.
on:
    workflow_call:
        inputs:
            ref:
                type: string
                default: main
                required: false
                description: The Github ref to check out of the core-product-release repo
        outputs:
            cli-version:
                value: ${{ jobs.get-version.outputs.cli-version }}
            cloud-version:
                value: ${{ jobs.get-version.outputs.cloud-version }}
            cloud-e2e-version:
                value: ${{ jobs.get-version.outputs.cloud-e2e-version }}
            core-fluent-bit-version:
                value: ${{ jobs.get-version.outputs.core-fluent-bit-version }}
            core-operator-version:
                value: ${{ jobs.get-version.outputs.core-operator-version }}
            configmap-reload-version:
                value: ${{ jobs.get-version.outputs.configmap-reload-version }}
            frontend-version:
                value: ${{ jobs.get-version.outputs.frontend-version }}
            lua-sandbox-version:
                value: ${{ jobs.get-version.outputs.lua-sandbox-version }}
            lua-modules-version:
                value: ${{ jobs.get-version.outputs.lua-modules-version }}
            ingest-checks-version:
                value: ${{ jobs.get-version.outputs.ingest-checks-version }}
            cloud-image:
                value: ${{ jobs.get-image.outputs.cloud-image }}
            core-fluent-bit-image:
                value: ${{ jobs.get-image.outputs.core-fluent-bit-image }}
            core-operator-image:
                value: ${{ jobs.get-image.outputs.core-operator-image }}
            core-operator-sync-to-image:
                value: ${{ jobs.get-image.outputs.core-operator-sync-to-image }}
            core-operator-sync-from-image:
                value: ${{ jobs.get-image.outputs.core-operator-sync-from-image }}
            configmap-reload-image:
                value: ${{ jobs.get-image.outputs.configmap-reload-image }}
            frontend-image:
                value: ${{ jobs.get-image.outputs.frontend-image }}
            lua-sandbox-image:
                value: ${{ jobs.get-image.outputs.lua-sandbox-image }}
            ingest-checks-image:
                value: ${{ jobs.get-image.outputs.ingest-checks-image }}
jobs:
    get-version:
        name: Get the core-product-release versions
        runs-on: ubuntu-latest
        permissions:
            # Public repo so no token required
            contents: none
        outputs:
            cli-version: ${{ steps.cli-version.outputs.version }}
            cloud-version: ${{ steps.cloud-version.outputs.version }}
            cloud-e2e-version: ${{ steps.cloud-e2e-version.outputs.version }}
            core-fluent-bit-version: ${{ steps.core-fluent-bit-version.outputs.version }}
            core-operator-version: ${{ steps.core-operator-version.outputs.version }}
            configmap-reload-version: ${{ steps.configmap-reload-version.outputs.version }}
            frontend-version: ${{ steps.frontend-version.outputs.version }}
            lua-sandbox-version: ${{ steps.lua-sandbox-version.outputs.version }}
            lua-modules-version: ${{ steps.lua-modules-version.outputs.version }}
            ingest-checks-version: ${{ steps.ingest-checks-version.outputs.version }}
        steps:
            - uses: actions/checkout@v4
              with:
                repository: chronosphereio/calyptia-core-product-release
                ref: ${{ inputs.ref }}

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y jq
              shell: bash

            - id: cli-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.cli component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: cloud-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.cloud component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: cloud-e2e-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.cloud_e2e component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-fluent-bit-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.core_fluent_bit component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-operator-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.core_operator component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: configmap-reload-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.configmap_reload component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: frontend-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.frontend component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: lua-sandbox-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.lua_sandbox component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: lua-modules-version
              continue-on-error: true
              run: |
                VERSION=$(jq -cr .versions.lua_modules component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

            - id: ingest-checks-version
              run: |
                VERSION=$(jq -cr .versions.core_sidecar_ingest_check component-config.json)
                echo "$VERSION"
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

    get-image:
        name: Get the core-product-release images
        runs-on: ubuntu-latest
        permissions:
            # Public repo so no token required
            contents: none
        outputs:
            cloud-image: ${{ steps.cloud-image.outputs.image }}
            core-fluent-bit-image: ${{ steps.core-fluent-bit-image.outputs.image }}
            core-operator-image: ${{ steps.core-operator-image.outputs.image }}
            core-operator-sync-to-image: ${{ steps.core-operator-sync-to-image.outputs.image }}
            core-operator-sync-from-image: ${{ steps.core-operator-sync-from-image.outputs.image }}
            configmap-reload-image: ${{ steps.configmap-reload-image.outputs.image }}
            frontend-image: ${{ steps.frontend-image.outputs.image }}
            lua-sandbox-image: ${{ steps.lua-sandbox-image.outputs.image }}
            ingest-checks-image: ${{ steps.ingest-checks-image.outputs.image }}
        steps:
            - uses: actions/checkout@v4
              with:
                repository: chronosphereio/calyptia-core-product-release
                ref: ${{ inputs.ref }}

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y jq
              shell: bash

            - id: cloud-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.cloud component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-fluent-bit-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.core_fluent_bit component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-operator-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.core_operator component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-operator-sync-to-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.core_operator_sync_to component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: core-operator-sync-from-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.core_operator_sync_from component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: configmap-reload-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.configmap_reload component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: frontend-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.frontend component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: lua-sandbox-image
              continue-on-error: true
              run: |
                IMAGE=$(jq -cr .containers.lua_sandbox component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash

            - id: ingest-checks-image
              run: |
                IMAGE=$(jq -cr .containers.core_sidecar_ingest_check component-config.json)
                echo "$IMAGE"
                echo "image=$IMAGE" >> $GITHUB_OUTPUT
              shell: bash
