name: Release
on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
jobs:
    ci-get-metadata:
        uses: ./.github/workflows/get-versions.yaml

    ci-release:
        name: Create official release
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        needs:
            - ci-get-metadata
        permissions:
            contents: write
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Create release for tag
          uses: softprops/action-gh-release@v1
          with:
            body: |
              Release of Calyptia Core ${{ github.ref_name }}:
                - CLI: ${{ needs.ci-get-metadata.outputs.cli-version }}
                - Cloud: ${{ needs.ci-get-metadata.outputs.cloud-version }}
                - Core: ${{ needs.ci-get-metadata.outputs.core-version }}
                - Core Fluent Bit: ${{ needs.ci-get-metadata.outputs.core-fluent-bit-version }}
                - Core Operator: ${{ needs.ci-get-metadata.outputs.core-operator-version }}
                - Frontend: ${{ needs.ci-get-metadata.outputs.frontend-version }}
                - LUA Sandbox: ${{ needs.ci-get-metadata.outputs.lua-sandbox-version }}
            fail_on_unmatched_files: false
            files: |
                *.json
            generate_release_notes: false