name: Run integration tests directly with specified versions
on:
    workflow_dispatch:
        inputs:
            cli-version:
              type: string
              required: false
              default: latest
              description: Release version of the calyptia cli to use, with the `v` prefix (release rather than numeric version)
            cli-image:
              type: string
              required: false
              default: ''
              description: CLI image to use to extract a custom binary from, only use this for PRs or similar.
            cloud-image:
              type: string
              required: false
              default: ghcr.io/calyptia/cloud:latest
              description: docker image of calyptia/cloud
            core-operator-image:
              type: string
              required: false
              default: ghcr.io/calyptia/core-operator:latest
              description: docker image of calyptia/core-operator
            core-operator-from-cloud-image:
              type: string
              required: false
              default: ghcr.io/calyptia/core-operator/sync-from-cloud:latest
              description: docker image of calyptia/core-operator
            core-operator-to-cloud-image:
              type: string
              required: false
              default: ghcr.io/calyptia/core-operator/sync-to-cloud:latest
              description: docker image of calyptia/core-operator
            calyptia-tests:
              description: Path to tests to be executed
              type: string
              required: false
            runner:
              description: The runner to use for tests.
              type: string
              required: false
              default: ubuntu-latest-m
            k8s-distribution:
              description: The K8S distribution to use for tests.
              type: choice
              options:
                - 'kind'
                - 'vcluster'
              default: kind
              required: false
jobs:
    ci-e2e-tests:
        uses: ./.github/workflows/call-integration-tests.yaml
        with:
          cli-version: ${{ inputs.cli-version }}
          cli-image: ${{ inputs.cli-image }}
          cloud-image: ${{ inputs.cloud-image }}
          core-operator-image: ${{ inputs.core-operator-image }}
          core-operator-from-cloud-image: ${{ inputs.core-operator-from-cloud-image }}
          core-operator-to-cloud-image: ${{ inputs.core-operator-to-cloud-image }}
          ref: ${{ github.ref }}
          calyptia-tests: ${{ inputs.calyptia-tests }}
          runner: ${{ inputs.runner }}
          k8s-distribution: ${{ inputs.k8s-distribution }}
        secrets:
          registry-username: ${{ secrets.CI_USERNAME }}
          registry-password: ${{ secrets.CI_PAT }}
          # Replace with playground key after: https://app.asana.com/0/1205042382663691/1205231066738712/f
          google-access-key: ${{ secrets.GCP_SA_KEY }}
          github-token: ${{ secrets.CI_PAT }}