name: Update specific product version
on:
    workflow_call:
        inputs:
            product:
                description: The JSON key for the product to update.
                required: true
                type: string
            version:
                description: The numeric (no v- prefix) version to update to.
                required: true
                type: string
        secrets:
            token:
                required: true
                description: The Github token to use for check out.
        outputs:
            pr:
                value: ${{ jobs.version-update.outputs.pr || '' }}
                description: The PR created, if any, or an empty string.
jobs:
    version-checks:
        name: Sanitise and check inputs
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
            product: ${{ inputs.product }}
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.token }}
                repository: calyptia/core-product-release

            - name: Check product exists
              run: grep -q '${{ inputs.product }}' ./component-config.json
              shell: bash

            - name: Get numeric version only
              id: version
              run: |
                VERSION=${{ inputs.version }}
                # Handle stripping the v prefix if present
                if [[ "$VERSION" =~ ^v?([0-9]+\.[0-9]+\.[0-9]+)$ ]] ; then
                    VERSION=${BASH_REMATCH[1]}
                    echo "Valid version string: $VERSION"
                else
                    echo "ERROR: Invalid semver string: $VERSION"
                fi
                echo "version=$VERSION" >> $GITHUB_OUTPUT
              shell: bash

    version-update:
        name: Update ${{ needs.version-checks.outputs.product }} to ${{ needs.version-checks.outputs.version }}
        runs-on: ubuntu-latest
        needs:
            - version-checks
        outputs:
            pr: ${{ steps.cpr.outputs.pull-request-number || '' }}
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.token }}
                repository: calyptia/core-product-release
            - run: |
                jq '.versions.${{ needs.version-checks.outputs.product }} = "${{ needs.version-checks.outputs.version }}"' ./component-config.json | tee ./component-config-new.json
                mv -f ./component-config-new.json ./component-config.json
              shell: bash

            - name: Generate PR - runs all the tests
              id: cpr
              uses: peter-evans/create-pull-request@v5
              with:
                commit-message: 'ci: update to latest versions'
                signoff: true
                # Repeated calls will sit on top of each other to test as one until merged
                branch: ci_update_versions_push
                delete-branch: true
                title: 'ci: update to latest Calyptia versions'
                # We need workflows permission so have to use the CI_PAT
                token: ${{ secrets.token }}
                labels: ci,automerge
                body: |
                  Update Calyptia versions
                  - ${{ needs.version-checks.outputs.product }} = "${{ needs.version-checks.outputs.version }}"

                  Github info:
                  - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
                draft: false

            - name: Check outputs
              if: ${{ steps.cpr.outputs.pull-request-number }}
              run: |
                echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
              shell: bash

            - name: Enable Pull Request Automerge
              if: ${{ steps.cpr.outputs.pull-request-number }}
              run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
              env:
                GH_TOKEN: ${{ secrets.token }}
