name: Update upstream releases
# We pull from here to prevent too much coupling upstream.
on:
  workflow_dispatch:
    inputs:
      cli-version:
        description: The new CLI version to use, no v prefix.
        required: true
        type: string
      cloud-version:
        description: The new Cloud version to use, no v prefix.
        required: true
        type: string
      cloud-e2e-version:
        description: The new cloud-e2e version to use, no v prefix.
        required: true
        type: string
      core-fluent-bit-version:
        description: The new Core Fluent Bit version to use, no v prefix.
        required: true
        type: string
      core-operator-version:
        description: The new Core Operator version to use, no v prefix.
        required: true
        type: string
      frontend-version:
        description: The new Frontend version to use, no v prefix.
        required: true
        type: string
      lua-sandbox-version:
        description: The new Cloud LUA Sandbox version to use, no v prefix.
        required: true
        type: string
      lua-modules-version:
        description: The new LUA Modules version to use, no v prefix.
        required: true
        type: string
  schedule:
    - cron: "0 7 * * *"

jobs:

  get-cli-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-cli
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-cloud-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-cloud
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-cloud-e2e-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-cloud
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-core-fluent-bit-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-core-fluent-bit
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-core-operator-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-core-operator
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-frontend-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-frontend
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-lua-sandbox-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-cloud-lua-sandbox
    secrets:
      token: ${{ secrets.CI_PAT }}

  get-lua-modules-release:
    uses: ./.github/workflows/get-latest-tag.yaml
    with:
      repo: calyptia-lua-modules
    secrets:
      token: ${{ secrets.CI_PAT }}

  update-versions:
    name: Update versions used
    runs-on: ubuntu-latest
    needs:
      - get-cli-release
      - get-cloud-release
      - get-cloud-e2e-release
      - get-core-fluent-bit-release
      - get-core-operator-release
      - get-frontend-release
      - get-lua-sandbox-release
      - get-lua-modules-release
    permissions:
      contents: read
      # Not required as we use CI_PAT directly so we can trigger workflows
      # pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}

      - name: Update versions
        # We want to ensure we do not overwrite anything else in the file, just versions.
        # Note we also cope with empty versions provided on input - this will then use latest.
        run: |
          jq '
          .versions.cli = "${{ inputs.cli-version || needs.get-cli-release.outputs.semver-tag }}" |
          .versions.cloud = "${{ inputs.cloud-version || needs.get-cloud-release.outputs.semver-tag }}" |
          .versions.cloud_e2e = "${{ inputs.cloud-e2e-version || needs.get-cloud-e2e-release.outputs.semver-tag }}" |
          .versions.core_fluent_bit = "${{ inputs.core-fluent-bit-version || needs.get-core-fluent-bit-release.outputs.semver-tag }}" |
          .versions.core_operator = "${{ inputs.core-operator-version || needs.get-core-operator-release.outputs.semver-tag }}" |
          .versions.frontend = "${{ inputs.frontend-version || needs.get-frontend-release.outputs.semver-tag }}" |
          .versions.lua_sandbox = "${{ inputs.lua-sandbox-version || needs.get-lua-sandbox-release.outputs.semver-tag }}" |
          .versions.lua_modules = "${{ inputs.lua-modules-version || needs.get-lua-modules-release.outputs.semver-tag }}"' ./component-config.json | tee ./component-config-new.json
          mv -f ./component-config-new.json ./component-config.json
        shell: bash

      - name: Generate PR - runs all the tests
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'ci: update to latest versions'
          signoff: true
          branch: ci_update_versions
          delete-branch: true
          title: 'ci: update to latest Calyptia versions'
          # We need workflows permission so have to use the CI_PAT
          token: ${{ secrets.CI_PAT }}
          labels: ci,automerge
          body: |
            Update Calyptia versions
            - CLI: ${{ inputs.cli-version || needs.get-cli-release.outputs.tag }}
            - Cloud: ${{ inputs.cloud-version || needs.get-cloud-release.outputs.tag }}
            - Cloud E2E: ${{ inputs.cloud-e2e-version || needs.get-cloud-release.outputs.tag }}
            - Core Fluent Bit: ${{ inputs.core-fluent-bit-version || needs.get-core-fluent-bit-release.outputs.tag }}
            - Core Operator: ${{ inputs.core-operator-version || needs.get-core-operator-release.outputs.tag }}
            - Frontend: ${{ inputs.frontend-version || needs.get-frontend-release.outputs.tag }}
            - Cloud LUA Sandbox: ${{ inputs.lua-sandbox-version || needs.get-lua-sandbox-release.outputs.tag }}
            - LUA Modules: ${{ inputs.lua-modules-version || needs.get-lua-modules-release.outputs.tag }}

            Github info:
            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        shell: bash

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
